1,0,Well Well1 reporting initial position Vector2(35.6075, 123.589) and radius 20
1,0,Well Well2 reporting initial position Vector2(-106.37, -12.6997) and radius 20
1,0,Well Well3 reporting initial position Vector2(-12.4616, -104.989) and radius 20
1,0,Well Well4 reporting initial position Vector2(-59.8404, 29.2279) and radius 20
1,0,Well Well5 reporting initial position Vector2(49.303, -101.649) and radius 20
771,6888238,Writing DCM images to file.
